### PR TITLE
Deletes weren't working because casing doesn't appear to be consisten…

### PR DESCRIPTION
**Pull request by stephenleemcfarland**
…t. Downcasing name everywhere so we always find the match.

### CODE REVIEW

**Comment by ptierno** [comment]
What version of windows are you using? There is a reason why the name is only being down cased on 2012 nodes. In not sure I understand the purpose of this PR.

**Comment by slmcfarland81** [comment]
I am using 2012 r2. For whatever reason the casing is different between user added, system default, and user edited page files. If you simply ignore case then you won't have to worry about these edge cases. I ran into the issue when I was trying to delete a page file that was previously edited through the windows UI. From the bug reported by someone else a few days ago I'm not the only one. I've forked it so you surely don't need to accept the PR but I think your module will benefit from the modifications I've made. 

Stephen M

**Comment by ptierno** [comment]
Thanks for this. I'll run it through some testing and probably merge it in
if all is good

**Comment by TheCraiggers** [comment]
I'm encountering this problem as well, so I can help test this PR too.

**Comment by TheCraiggers** [comment]
I've did some testing and it at least fixes this specific issue. I don't have a ton of machines to test with yet though, I'm only testing with W2012.

**Comment by glarizza** [comment]
I tested this branch/code out with a customer, and it's working for me on Windows 2012R2.  👍

**Comment by TheCraiggers** [comment]
Shit guys, if fucking Gary Larizza says it is good, you should merge it already. :D

**Pull request merged**
